recastrestapi:
  build: .
  ports:
   - "5000:5000"
  volumes:
   - ./recastrestapi:/recast-rest-api/recastrestapi
   - ./config.yaml:/recast-rest-api/recastrestapi/resources/defaultconfig.yaml
  links:
   - db

db:
  image: postgres
  ports:
   - "5432:5432"