ORCID_APPID: 'ORCID_APPID'
ORCID_REDIRECT_URI: 'ORCID_REDIRECT_URI'
ORCID_SECRET: 'ORCID_SECRET'
HOSTNAME: 'localhost'
REDISURL: 'redis://localhost:6379/0'
CELERYAPP: 'recastfrontend.celeryapp'
FLASKCONFIG: 'recastfrontend.flaskconfig'
DBPATH: 'postgres://nownhnjimayuwk:LVfBGoYAcG8UGc0KdtERuwGK8m@ec2-54-225-215-233.compute-1.amazonaws.com:5432/d3e5kjpch43v11'