ORCID_APPID: 'ORCID_APPID'
ORCID_REDIRECT_URI: 'ORCID_REDIRECT_URI'
ORCID_SECRET: 'ORCID_SECRET'
HOSTNAME: 'localhost'
REDISURL: 'redis://localhost:6379/0'
CELERYAPP: 'recastfrontend.celeryapp'
FLASKCONFIG: 'recastfrontend.flaskconfig'
AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID'
AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY'
AWS_S3_BUCKET_NAME: 'AWS_S3_BUCKET_NAME'
ZENODO_ACCESS_TOKEN: 'ZENODO_ACCESS_TOKEN'
DBPATH: 'sqlite:///tmp.db'